const tagObj = {
  "2022-presidential-election": { text: "대선", icon: "🎈" },
  politics: { text: "정치", icon: "🍘" },
  economy: { text: "경제", icon: "🍔" },
  world: { text: "세계", icon: "🍕" },
  tech: { text: "테크", icon: "🍳" },
  labor: { text: "노동", icon: "🍳" },
  "new-normal": { text: "뉴노멀", icon: "🥗" },
  culture: { text: "문화", icon: "🍎" },
  life: { text: "라이프", icon: "🥙" },
  community: { text: "커뮤니티", icon: "🎅" },
};
export default tagObj;
// { text: "전체", url: "/", icon: "" },
// { text: "대선", url: "/tag/2022-presidential-election", icon: "" },
// { text: "정치", url: "/tag/politics", icon: "" },
// { text: "경제", url: "/tag/economy", icon: "" },
// { text: "세계", url: "/tag/world", icon: "" },
// { text: "테크", url: "/tag/tech", icon: "" },
// { text: "노동", url: "/tag/labor", icon: "" },
// { text: "뉴노멀", url: "/tag/new-normal", icon: "" },
// { text: "문화", url: "/tag/culture", icon: "" },
// { text: "라이프", url: "/tag/life", icon: "" },
// { text: "커뮤니티", url: "/tag/community", icon: "" },
